### ISSUE TITLE
Update python

### ISSUE THREAD

**Issue by hschallh** [OSU-CS/automod#17]
## Description
While deploying, heroku spat out the following warning
> Python has released a security update! Please consider upgrading to python-3.7.5

## Acceptance Criteria
- [ ] Python is upgraded to 3.7.5

## Extra
[Heroku supported runtimes](https://devcenter.heroku.com/articles/python-support#supported-runtimes). [Specifying python version in heroku](https://devcenter.heroku.com/articles/python-runtimes).

**Comment by sarahmaas** [comment]
#37 bumped to 3.7.13
